[theme]
base            = "dark"
backgroundColor = "#070912"
secondaryBackgroundColor = "#0f1326"
textColor       = "#e8ecf6"
primaryColor    = "#00e5ff"
font            = "sans serif"

[server]
headless        = true
enableCORS      = false
port            = 8501

[browser]
gatherUsageStats = false
